---
# SPDX-License-Identifier: MIT
# defaults file for docker

docker_fedora_packages:
  - docker-ce
  - docker-ce-cli
  - docker-buildx-plugin
  - docker-compose-plugin
  - containerd.io
  - container-selinux
