---
- name: Verify
  hosts: molecule
  gather_facts: true
  tasks:
    - name: Stat the docker yum repo file
      ansible.builtin.stat:
        path: /etc/yum.repos.d/docker-ce.repo
      register: docker_repo

    - name: Assert docker yum repo is installed
      ansible.builtin.assert:
        that:
          - docker_repo.stat.exists

    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: rpm

    - name: Assert docker-ce is installed
      ansible.builtin.assert:
        that:
          - "'docker-ce' in ansible_facts.packages"

    - name: Assert docker-ce-cli is installed
      ansible.builtin.assert:
        that:
          - "'docker-ce-cli' in ansible_facts.packages"

    - name: Assert container-selinux is installed
      ansible.builtin.assert:
        that:
          - "'container-selinux' in ansible_facts.packages"

    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Assert docker.service is enabled
      ansible.builtin.assert:
        that:
          - ansible_facts.services['docker.service']['status'] == 'enabled'

    - name: Look up the docker group
      ansible.builtin.getent:
        database: group
        key: docker

    - name: Assert docker group exists
      ansible.builtin.assert:
        that:
          - ansible_facts.getent_group['docker'] is defined

    - name: Read ansible user group membership
      ansible.builtin.command:
        cmd: id -nG ansible
      register: docker_ansible_groups
      changed_when: false

    - name: Assert ansible user is in docker group
      ansible.builtin.assert:
        that:
          - "'docker' in docker_ansible_groups.stdout.split()"
