---
- name: Destroy molecule instance
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Stop and remove common-fedora-instance container
      containers.podman.podman_container:
        name: common-fedora-instance
        state: absent
