---
# SPDX-License-Identifier: MIT
galaxy_info:
  role_name: arcane
  namespace: danmwallace
  author: Dan Wallace
  description: Deploy Arcane, a modern web UI for managing Docker containers, via Docker Compose.
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Debian
      versions:
        - bookworm
    - name: Ubuntu
      versions:
        - jammy
        - noble
    - name: Fedora
      versions:
        - all
  galaxy_tags:
    - docker
    - arcane
    - container
    - management
    - webui
    - traefik

dependencies: []
