---
- name: Destroy molecule instance
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Stop and remove grafana-instance container
      containers.podman.podman_container:
        name: grafana-instance
        state: absent
